application: 4sqmatch
version: 1
runtime: python
api_version: 1

handlers:
- url: /
  static_files: index.html
  upload: index.html
  expiration: 0
- url: /static
  static_dir: static
- url: /.*
  script: main.py
